resource_group                = "Bhushan-RG"
location                      = "East US"
azurerm_virtual_network       = "ProdVnet"
address_space                 = ["10.0.0.0/16"]
address_prefixes              = ["10.0.1.0/24"]
azurerm_subnet                = "internal"
azurerm_network_interface     = "Prod-NIC"
azurerm_linux_virtual_machine = "ProdLinuxVM"
size                          = ["Standard_B2s"]
